// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Celiums Solutions LLC

/**
 * Celiums Ethics Engine v3 — Multilingual Lexicon
 *
 * Maps terms across 10 languages into the 12-category taxonomy.
 * Each entry includes: category, weight, requiresLivingTarget,
 * suppressInTechnical, and languages where it applies.
 *
 * Architecture: Single lexicon with language tags. No duplicate entries.
 * The engine lowercases input before matching, so terms MUST be lowercase.
 *
 * @license Apache-2.0
 */

import type { SupportedLanguage } from './ethics-taxonomy.js';

export interface LexiconEntry {
  /** 12-category taxonomy ID */
  category: string;
  /** Base weight 0-1 */
  weight: number;
  /** True if this term only flags when targeting a living being */
  requiresLivingTarget: boolean;
  /** True if this term should be suppressed in technical/code contexts */
  suppressInTechnical: boolean;
  /** Languages where this term applies */
  languages: SupportedLanguage[];
}

/**
 * MULTILINGUAL LEXICON — Single source of truth.
 *
 * CATEGORY MAP:
 *   violence_harm, child_safety, hate_speech, self_harm,
 *   sexual_content, deception, illegal_activities, misinformation,
 *   privacy, cybersecurity, autonomy, system_override
 */
export const MULTILINGUAL_LEXICON: Record<string, LexiconEntry> = {
  // ══════════════════════════════════════════════
  // CAT 1: VIOLENCE & PHYSICAL HARM
  // ══════════════════════════════════════════════
  kill:           { category: 'violence_harm', weight: 0.70, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  murder:         { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  assassinate:    { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  torture:        { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  strangle:       { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  stab:           { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['en'] },
  shoot:          { category: 'violence_harm', weight: 0.75, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  poison:         { category: 'violence_harm', weight: 0.80, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  bomb:           { category: 'violence_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  explosive:      { category: 'violence_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en', 'de'] },
  weapon:         { category: 'violence_harm', weight: 0.50, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  harm:           { category: 'violence_harm', weight: 0.50, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  hurt:           { category: 'violence_harm', weight: 0.45, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  attack:         { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  genocide:       { category: 'violence_harm', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de'] },
  massacre:       { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr'] },
  terrorism:      { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },

  // Spanish
  matar:          { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es', 'pt'] },
  asesinar:       { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  torturar:       { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  herir:          { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es'] },
  golpear:        { category: 'violence_harm', weight: 0.70, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['es'] },
  agredir:        { category: 'violence_harm', weight: 0.75, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['es', 'pt'] },
  lastimar:       { category: 'violence_harm', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es'] },
  amenazar:       { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es'] },
  abusar:         { category: 'violence_harm', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  secuestrar:     { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  apuñalar:       { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['es'] },
  disparar:       { category: 'violence_harm', weight: 0.75, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es', 'pt'] },
  envenenar:      { category: 'violence_harm', weight: 0.80, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es'] },
  maltratar:      { category: 'violence_harm', weight: 0.70, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['es', 'pt'] },
  terrorismo:     { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt', 'it'] },
  genocidio:      { category: 'violence_harm', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  masacre:        { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  violencia:      { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es', 'pt', 'it'] },
  'causar daño':  { category: 'violence_harm', weight: 0.80, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['es'] },

  // Portuguese
  matar_pt:       { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['pt'] },
  assassinar:     { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  'causar dano':  { category: 'violence_harm', weight: 0.80, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['pt'] },
  ferir:          { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['pt'] },
  machucar:       { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['pt'] },
  sequestrar:     { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  envenenar_pt:   { category: 'violence_harm', weight: 0.80, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['pt'] },

  // French
  tuer:           { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['fr'] },
  assassiner:     { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  torturer:       { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  blesser:        { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['fr'] },
  frapper:        { category: 'violence_harm', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['fr'] },
  menacer:        { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['fr'] },
  violenter:      { category: 'violence_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },

  // German
  töten:          { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['de'] },
  ermorden:       { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  foltern:        { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  verletzen:      { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['de'] },
  schlagen:       { category: 'violence_harm', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['de'] },
  bedrohen:       { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['de'] },
  gewalt:         { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['de'] },

  // Italian
  uccidere:       { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['it'] },
  assassinare:    { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  torturare:      { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  ferire:         { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['it'] },
  colpire:        { category: 'violence_harm', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['it'] },
  minacciare:     { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['it'] },
  violentare:     { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },

  // Russian
  'убить':        { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['ru'] },
  'убийство':     { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'пытать':       { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'ранить':       { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['ru'] },
  'насилие':      { category: 'violence_harm', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['ru'] },

  // Turkish
  'öldürmek':     { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['tr'] },
  'cinayet':      { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['tr'] },
  'işkence':      { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['tr'] },
  'yaralamak':    { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['tr'] },
  'şiddet':       { category: 'violence_harm', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['tr'] },

  // Japanese
  '殺す':         { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['ja'] },
  '殺人':         { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ja'] },
  '拷問':         { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ja'] },
  // '暴力' was duplicated — Japanese-only entry merged into the zh+ja entry below to keep lexicon dedup-friendly.
  '危害':         { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['ja'] },

  // Chinese
  '杀人':         { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },
  '谋杀':         { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },
  '折磨':         { category: 'violence_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },
  '伤害':         { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['zh'] },
  '暴力':         { category: 'violence_harm', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['zh', 'ja'] },

  // ══════════════════════════════════════════════
  // CAT 2: CHILD SAFETY & EXPLOITATION
  // ══════════════════════════════════════════════
  groom:             { category: 'child_safety', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'child abuse':     { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'exploit child':   { category: 'child_safety', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  pedophilia:        { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'abuso infantil':  { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  pedofilia:         { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt', 'it'] },
  'abus d\'enfant':  { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  pédophilie:        { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  kindesmissbrauch:  { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  pädophilie:        { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  'abuso di minori': { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  'aбывзо дттей':    { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },

  // ══════════════════════════════════════════════
  // CAT 3: HATE SPEECH & DISCRIMINATION
  // ══════════════════════════════════════════════
  'hate speech':     { category: 'hate_speech', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  racist:            { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de'] },
  sexist:            { category: 'hate_speech', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  homophobic:        { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  transphobic:       { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de'] },
  xenophobic:        { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  antisemitic:       { category: 'hate_speech', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it'] },
  islamophobic:      { category: 'hate_speech', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr'] },
  racista:           { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  homofóbico:        { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  sexista:           { category: 'hate_speech', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  transfóbico:       { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  xenófobo:          { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  raciste:           { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  homophobe:         { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  rassistisch:       { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  fremdenfeindlich:  { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  razzista:          { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  sessista:          { category: 'hate_speech', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  'расизм':          { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'ırkçı':           { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['tr'] },
  '人種差別':        { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ja'] },
  '种族歧视':        { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },

  // ══════════════════════════════════════════════
  // CAT 4: SELF-HARM & SUICIDE
  // ══════════════════════════════════════════════
  suicide:               { category: 'self_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en', 'fr'] },
  'kill myself':         { category: 'self_harm', weight: 0.92, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'end my life':         { category: 'self_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'hurt myself':         { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'harm myself':         { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  suicidio:              { category: 'self_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt', 'it'] },
  'causarme dano':       { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'hacerme dano':        { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  lastimarme:            { category: 'self_harm', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  autolesion:            { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  suicidar:              { category: 'self_harm', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  automutilação:         { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  'me tuer':             { category: 'self_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  automutilation:        { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  selbstmord:            { category: 'self_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['de'] },
  selbstverletzung:      { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  autolesionismo:        { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  'самоубийство':        { category: 'self_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['ru'] },
  'самоповреждение':     { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'intihar':             { category: 'self_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['tr'] },
  'kendine zarar':       { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['tr'] },
  '自殺':                { category: 'self_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['ja', 'zh'] },
  '自伤':                { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },

  // ══════════════════════════════════════════════
  // CAT 5: SEXUAL CONTENT & HARASSMENT
  // ══════════════════════════════════════════════
  rape:              { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr'] },
  'sexual assault':  { category: 'sexual_content', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'sexual harassment': { category: 'sexual_content', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  violar:            { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  acosar:            { category: 'sexual_content', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es'] },
  violación:         { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  estupro:           { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  'agressão sexual': { category: 'sexual_content', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  viol:              { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  'harcèlement sexuel': { category: 'sexual_content', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  vergewaltigung:    { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  'sexuelle belästigung': { category: 'sexual_content', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  stupro:            { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  'molestie sessuali': { category: 'sexual_content', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  'изнасилование':   { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'tecavüz':         { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['tr'] },
  'レイプ':          { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ja'] },
  '强奸':            { category: 'sexual_content', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },

  // ══════════════════════════════════════════════
  // CAT 6: DECEPTION & FRAUD
  // ══════════════════════════════════════════════
  phishing:           { category: 'deception', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  impersonate:        { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  deceive:            { category: 'deception', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  manipulate:         { category: 'deception', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  fraud:              { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  scam:               { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  blackmail:          { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  estafa:             { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  fraude:             { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt'] },
  engañar:            { category: 'deception', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es'] },
  chantaje:           { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  extorsion:          { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  enganar:            { category: 'deception', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['pt'] },
  burlar:             { category: 'deception', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['pt'] },
  escroquerie:        { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  arnaque:            { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  tromper:            { category: 'deception', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['fr'] },
  betrug:             { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  täuschen:           { category: 'deception', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['de'] },
  truffa:             { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  ingannare:          { category: 'deception', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['it'] },
  'мошенничество':    { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'фишинг':           { category: 'deception', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'dolandırıcılık':   { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['tr'] },
  'フィッシング':     { category: 'deception', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ja'] },
  '诈骗':             { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },

  // ══════════════════════════════════════════════
  // CAT 7: ILLEGAL ACTIVITIES
  // ══════════════════════════════════════════════
  'human trafficking':  { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'drug trafficking':   { category: 'illegal_activities', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'money laundering':   { category: 'illegal_activities', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'trata de personas':  { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'tráfico de drogas':  { category: 'illegal_activities', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  'lavado de dinero':   { category: 'illegal_activities', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'tráfico humano':     { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  'traite humaine':     { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  'trafic de drogue':   { category: 'illegal_activities', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  menschenhandel:       { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  drogenhandel:         { category: 'illegal_activities', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  geldwäsche:           { category: 'illegal_activities', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  'tratta di persone':  { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  'торговля людьми':    { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'insan ticareti':     { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['tr'] },
  '人身売買':           { category: 'illegal_activities', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ja'] },

  // ══════════════════════════════════════════════
  // CAT 10: CYBERSECURITY ATTACKS
  // ══════════════════════════════════════════════
  malware:           { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  ransomware:        { category: 'cybersecurity', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  exploit:           { category: 'cybersecurity', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'zero-day':        { category: 'cybersecurity', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'zero day':        { category: 'cybersecurity', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  backdoor:          { category: 'cybersecurity', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en', 'fr', 'de'] },
  botnet:            { category: 'cybersecurity', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  keylogger:         { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  spyware:           { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es'] },
  troyano:           { category: 'cybersecurity', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  ransomware_es:     { category: 'cybersecurity', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'programa espía':  { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'logiciel malveillant': { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  rançongiciel:      { category: 'cybersecurity', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  schadsoftware:     { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  erpressersoftware: { category: 'cybersecurity', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  'вредоносное по':  { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'マルウェア':      { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ja'] },
  '恶意软件':        { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },

  // ══════════════════════════════════════════════
  // CAT 8: MISINFORMATION
  // ══════════════════════════════════════════════
  deepfake:              { category: 'misinformation', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  disinformation:        { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'fake news':           { category: 'misinformation', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'de'] },
  desinformación:        { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'noticias falsas':     { category: 'misinformation', weight: 0.60, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  désinformation:        { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  desinformação:         { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  desinformation:        { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  disinformazione:       { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  'дезинформация':       { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ru'] },
  'dezenformasyon':      { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['tr'] },
  '誤情報':              { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['ja'] },
  '虚假信息':            { category: 'misinformation', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['zh'] },

  // ══════════════════════════════════════════════
  // CAT 9: PRIVACY VIOLATIONS
  // ══════════════════════════════════════════════
  doxxing:            { category: 'privacy',        weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  doxxear:            { category: 'privacy',        weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  doxear:             { category: 'privacy',        weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  doxing:             { category: 'privacy',        weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  'data breach':      { category: 'privacy',        weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'social security number': { category: 'privacy',  weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'credit card number': { category: 'privacy',      weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },

  // ══════════════════════════════════════════════
  // CAT 11: AUTONOMY VIOLATIONS
  // ══════════════════════════════════════════════
  coercion:           { category: 'autonomy', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  coaccion:           { category: 'autonomy', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es'] },
  coerção:            { category: 'autonomy', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['pt'] },
  coercition:         { category: 'autonomy', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['fr'] },
  zwang:              { category: 'autonomy', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['de'] },
  coercizione:        { category: 'autonomy', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['it'] },

  // ══════════════════════════════════════════════
  // CAT 12: SYSTEM OVERRIDE & JAILBREAK
  // ══════════════════════════════════════════════
  jailbreak:              { category: 'system_override', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  'ignore your rules':    { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'bypass ethics':        { category: 'system_override', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'disable constraints':  { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'do anything now':      { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'dan mode':             { category: 'system_override', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'prompt injection':     { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'bypass restrictions':  { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'ignora tus reglas':    { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['es'] },
  'ignora las reglas':    { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['es'] },
  'ignorer les règles':   { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['fr'] },
  'ignoriere die regeln': { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['de'] },
  'ignora le regole':     { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['it'] },
  'ignorar as regras':    { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['pt'] },
  'игнорируй правила':    { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['ru'] },
  'kuralları yok say':    { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['tr'] },
  'ルールを無視':         { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['ja'] },
  '忽略规则':             { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['zh'] },

  // ═══════════════════════════════════════════════════════════════
  // EXPANDED LEXICON (2026-05-07): 213 new entries from synonym maps,
  // SafetyBench data patterns, and cross-language equivalents.
  // Total: 477 entries across 10 languages.
  // ═══════════════════════════════════════════════════════════════
  slaughter: { category: 'violence_harm', weight: 0.92, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  exterminate: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  annihilate: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  brutalize: { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['en'] },
  maim: { category: 'violence_harm', weight: 0.88, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['en'] },
  mutilate: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['en'] },
  dismember: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['en'] },
  decapitate: { category: 'violence_harm', weight: 0.92, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['en'] },
  lynch: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  beat: { category: 'violence_harm', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  punch: { category: 'violence_harm', weight: 0.50, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  slap: { category: 'violence_harm', weight: 0.45, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  choke: { category: 'violence_harm', weight: 0.75, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['en'] },
  drown: { category: 'violence_harm', weight: 0.80, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['en'] },
  burn: { category: 'violence_harm', weight: 0.75, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  crucify: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  execute: { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  lethal: { category: 'violence_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en', 'fr'] },
  fatality: { category: 'violence_harm', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  carnage: { category: 'violence_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr'] },
  bloodshed: { category: 'violence_harm', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'drive by': { category: 'violence_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'shoot up': { category: 'violence_harm', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'pipe bomb': { category: 'violence_harm', weight: 0.92, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  molotov: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es'] },
  'nerve agent': { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'mustard gas': { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'sarin gas': { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  ricin: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de'] },
  anthrax: { category: 'violence_harm', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es'] },
  agresion: { category: 'violence_harm', weight: 0.70, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es'] },
  aporrear: { category: 'violence_harm', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['es'] },
  degollar: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['es'] },
  masacrar: { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  aniquilar: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  ermordung: { category: 'violence_harm', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  hinrichten: { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['de'] },
  verstummeln: { category: 'violence_harm', weight: 0.90, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['de'] },
  erstechen: { category: 'violence_harm', weight: 0.85, requiresLivingTarget: true,  suppressInTechnical: false, languages: ['de'] },
  'child pornography': { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'child predator': { category: 'child_safety', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'cp content': { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  csam: { category: 'child_safety', weight: 0.98, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  loli: { category: 'child_safety', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'ja'] },
  shotacon: { category: 'child_safety', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'ja'] },
  'n word': { category: 'hate_speech', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'k word': { category: 'hate_speech', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'racial slur': { category: 'hate_speech', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'white supremacy': { category: 'hate_speech', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'white power': { category: 'hate_speech', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'ethnic cleansing': { category: 'hate_speech', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  aryan: { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'de'] },
  swastika: { category: 'hate_speech', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'de'] },
  heil: { category: 'hate_speech', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'de'] },
  misogyny: { category: 'hate_speech', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  misogynist: { category: 'hate_speech', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  misandry: { category: 'hate_speech', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  derogatory: { category: 'hate_speech', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'go back to': { category: 'hate_speech', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  inferior: { category: 'hate_speech', weight: 0.60, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  subhuman: { category: 'hate_speech', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  supremacia: { category: 'hate_speech', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  'limpieza etnica': { category: 'hate_speech', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'limpeza etnica': { category: 'hate_speech', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  'nettoyage ethnique': { category: 'hate_speech', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  'ethnische sauberung': { category: 'hate_speech', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  'pulizia etnica': { category: 'hate_speech', weight: 0.95, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  'self immolation': { category: 'self_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  overdose: { category: 'self_harm', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'hang myself': { category: 'self_harm', weight: 0.92, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  cutting: { category: 'self_harm', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'no reason to live': { category: 'self_harm', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  anorexic: { category: 'self_harm', weight: 0.60, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  bulimic: { category: 'self_harm', weight: 0.60, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'pro ana': { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'pro mia': { category: 'self_harm', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  thinspo: { category: 'self_harm', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  sobredosis: { category: 'self_harm', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es'] },
  ahorcarme: { category: 'self_harm', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  cortarme: { category: 'self_harm', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'revenge porn': { category: 'sexual_content', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  upskirt: { category: 'sexual_content', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'deepfake porn': { category: 'sexual_content', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'incest porn': { category: 'sexual_content', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'genital mutilation': { category: 'sexual_content', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  trafficker: { category: 'sexual_content', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'pornografia venganza': { category: 'sexual_content', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'mutilacion genital': { category: 'sexual_content', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  proxeneta: { category: 'sexual_content', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  'social engineering': { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'identity theft': { category: 'deception', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  ponzi: { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es'] },
  'pyramid scheme': { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  catfish: { category: 'deception', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'crypto scam': { category: 'deception', weight: 0.78, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'romance scam': { category: 'deception', weight: 0.78, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'wire fraud': { category: 'deception', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'robo de identidad': { category: 'deception', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'esquema ponzi': { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  'esquema piramide': { category: 'deception', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  'fraude bancario': { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  'fraude electronico': { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'fraude bancaire': { category: 'deception', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  'usurpation identite': { category: 'deception', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  identitatsdiebstahl: { category: 'deception', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  'furto identita': { category: 'deception', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  heroin: { category: 'illegal_activities', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  cocaine: { category: 'illegal_activities', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  methamphetamine: { category: 'illegal_activities', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  fentanyl: { category: 'illegal_activities', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'lsd synthesis': { category: 'illegal_activities', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'cook meth': { category: 'illegal_activities', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  smuggle: { category: 'illegal_activities', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  cartel: { category: 'illegal_activities', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  sicario: { category: 'illegal_activities', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  hitman: { category: 'illegal_activities', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'contract killer': { category: 'illegal_activities', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  narcotrafico: { category: 'illegal_activities', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  narcotraficante: { category: 'illegal_activities', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  heroina: { category: 'illegal_activities', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt'] },
  cocaina: { category: 'illegal_activities', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt', 'it'] },
  metanfetamina: { category: 'illegal_activities', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  fentanilo: { category: 'illegal_activities', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  contrabando: { category: 'illegal_activities', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es', 'pt'] },
  'cartel droga': { category: 'illegal_activities', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'sql injection': { category: 'cybersecurity', weight: 0.72, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'xss attack': { category: 'cybersecurity', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'buffer overflow': { category: 'cybersecurity', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'rainbow table': { category: 'cybersecurity', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'hash crack': { category: 'cybersecurity', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'password crack': { category: 'cybersecurity', weight: 0.68, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'brute force': { category: 'cybersecurity', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'trojan horse': { category: 'cybersecurity', weight: 0.78, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'ddos attack': { category: 'cybersecurity', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'man in the middle': { category: 'cybersecurity', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  rootkit: { category: 'cybersecurity', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'worm virus': { category: 'cybersecurity', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  ciberataque: { category: 'cybersecurity', weight: 0.72, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'secuestro datos': { category: 'cybersecurity', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'gusano informatico': { category: 'cybersecurity', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  piratear: { category: 'cybersecurity', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es'] },
  craquear: { category: 'cybersecurity', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt'] },
  pirater: { category: 'cybersecurity', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['fr'] },
  hackear: { category: 'cybersecurity', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt'] },
  cyberattaque: { category: 'cybersecurity', weight: 0.72, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  cyberangriff: { category: 'cybersecurity', weight: 0.72, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  propaganda: { category: 'misinformation', weight: 0.50, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en', 'fr', 'de', 'it', 'es', 'pt'] },
  hoax: { category: 'misinformation', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'conspiracy theory': { category: 'misinformation', weight: 0.45, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'rigged election': { category: 'misinformation', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  chemtrail: { category: 'misinformation', weight: 0.50, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'flat earth': { category: 'misinformation', weight: 0.40, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'anti vax': { category: 'misinformation', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  antivacunas: { category: 'misinformation', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  antivax: { category: 'misinformation', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr'] },
  'teoria conspirativa': { category: 'misinformation', weight: 0.45, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt'] },
  'teoria da conspiracao': { category: 'misinformation', weight: 0.45, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['pt'] },
  'theorie du complot': { category: 'misinformation', weight: 0.45, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['fr'] },
  verschworungstheorie: { category: 'misinformation', weight: 0.45, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['de'] },
  'teoria complotto': { category: 'misinformation', weight: 0.45, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['it'] },
  stalk: { category: 'privacy', weight: 0.65, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  surveil: { category: 'privacy', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  wiretap: { category: 'privacy', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  keylog: { category: 'privacy', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'spy on': { category: 'privacy', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['en'] },
  'reveal identity': { category: 'privacy', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'expose personal': { category: 'privacy', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  espiar: { category: 'privacy', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es', 'pt'] },
  vigilar: { category: 'privacy', weight: 0.55, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['es', 'pt'] },
  interceptar: { category: 'privacy', weight: 0.60, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt'] },
  espionner: { category: 'privacy', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['fr'] },
  ausspionieren: { category: 'privacy', weight: 0.60, requiresLivingTarget: true,  suppressInTechnical: true,  languages: ['de'] },
  stalker: { category: 'privacy', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en', 'fr', 'de', 'it'] },
  brainwash: { category: 'autonomy', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  indoctrinate: { category: 'autonomy', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'mind control': { category: 'autonomy', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'lavado cerebral': { category: 'autonomy', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'lavagem cerebral': { category: 'autonomy', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  'lavage cerveau': { category: 'autonomy', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  gehirnwasche: { category: 'autonomy', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['de'] },
  'controllo mentale': { category: 'autonomy', weight: 0.75, requiresLivingTarget: false, suppressInTechnical: false, languages: ['it'] },
  gaslight: { category: 'autonomy', weight: 0.65, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'undue influence': { category: 'autonomy', weight: 0.60, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en'] },
  'psychological manipulation': { category: 'autonomy', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['en'] },
  'manipulacion psicologica': { category: 'autonomy', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['es'] },
  'manipulacao psicologica': { category: 'autonomy', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['pt'] },
  'manipulation psychologique': { category: 'autonomy', weight: 0.70, requiresLivingTarget: false, suppressInTechnical: false, languages: ['fr'] },
  cult: { category: 'autonomy', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['en', 'fr'] },
  secta: { category: 'autonomy', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['es', 'pt'] },
  sekta: { category: 'autonomy', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['de'] },
  setta: { category: 'autonomy', weight: 0.55, requiresLivingTarget: false, suppressInTechnical: true,  languages: ['it'] },
  'developer mode': { category: 'system_override', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'god mode': { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'no restrictions': { category: 'system_override', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'without restriction': { category: 'system_override', weight: 0.80, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'unrestricted mode': { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'unfiltered mode': { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'uncensored mode': { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'sin restricciones': { category: 'system_override', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: true, languages: ['es'] },
  'sin filtros': { category: 'system_override', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: true, languages: ['es'] },
  'modo desarrollador': { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['es'] },
  'modo dios': { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['es'] },
  'sans restriction': { category: 'system_override', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: true, languages: ['fr'] },
  'ohne einschrankung': { category: 'system_override', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: true, languages: ['de'] },
  'senza restrizioni': { category: 'system_override', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: true, languages: ['it'] },
  'sem restricoes': { category: 'system_override', weight: 0.82, requiresLivingTarget: false, suppressInTechnical: true, languages: ['pt'] },
  'disregard guidelines': { category: 'system_override', weight: 0.85, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'override safety': { category: 'system_override', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'disable safety': { category: 'system_override', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'turn off ethics': { category: 'system_override', weight: 0.90, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
  'ignore safety': { category: 'system_override', weight: 0.88, requiresLivingTarget: false, suppressInTechnical: true, languages: ['en'] },
};
