// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Celiums Solutions LLC

/**
 * Mode selection + migration — implements ADR-022 §"Mode selection
 * mechanics" + §"Anti-patterns refused".
 *
 * Invariants:
 *   - The install wizard MUST ask the user explicitly. Default on Lite
 *     is local-only; default on Standard is cloud-synced (ZK).
 *     cloud-managed is NEVER auto-selected.
 *   - Encryption is mandatory in cloud-synced. There is no
 *     "cloud-synced with encryption off" config.
 *   - Migration between modes is one-shot at the tenant scope and is
 *     recorded with selectedAt for forensic clarity.
 */

import type { SyncContext, SyncMode } from './types.js';
import { SyncRefusal } from './types.js';

export type Tier = 'lite' | 'standard' | 'enterprise';

/** Compute the **default offered** mode for a tier. Never auto-applies;
 *  the wizard surfaces this as the pre-selected option for the prompt. */
export function defaultModeForTier(tier: Tier): SyncMode {
  switch (tier) {
    case 'lite':
      return 'local-only';
    case 'standard':
      return 'cloud-synced';
    case 'enterprise':
      // Enterprise can opt-in to cloud-managed, but never as silent
      // default. The wizard pre-selects cloud-synced and shows
      // cloud-managed as an explicit choice with a DPA gate.
      return 'cloud-synced';
  }
}

export interface InstallWizardOpts {
  tier: Tier;
  /** What the user picked at the prompt. */
  chosen: SyncMode;
  /** True iff the user accepted the DPA. Required for cloud-managed. */
  dpaAccepted?: boolean;
  /** Tenant + user scope. */
  scope: { tenantId: string | null; userId: string };
  /** Optional clock for tests. */
  now?: () => Date;
}

/** Validate the user's choice and yield a SyncContext. Throws SyncRefusal
 *  on anti-pattern violations. */
export function commitInstallChoice(opts: InstallWizardOpts): SyncContext {
  if (opts.chosen === 'cloud-managed' && !opts.dpaAccepted) {
    throw new SyncRefusal(
      'cloud-managed requires explicit DPA acceptance — refusing silent default',
    );
  }
  const now = (opts.now ?? (() => new Date()))();
  return {
    mode: opts.chosen,
    scope: opts.scope,
    selectedAt: now.toISOString(),
  };
}

export interface MigrationPlan {
  from: SyncMode;
  to: SyncMode;
  /** What concretely happens. Generated by planModeMigration. */
  steps: string[];
  /** True iff the migration is destructive (e.g. losing ZK by going to
   *  cloud-managed exposes plaintext to the server). The wizard MUST
   *  surface this warning before executing. */
  exposesPlaintext: boolean;
}

/** Generate a plan for migrating from one mode to another. The wizard
 *  surfaces this for the user's review before invoking the real
 *  migration tooling. */
export function planModeMigration(from: SyncMode, to: SyncMode): MigrationPlan {
  if (from === to) {
    return { from, to, steps: ['no-op: already in target mode'], exposesPlaintext: false };
  }
  const steps: string[] = [];
  let exposesPlaintext = false;

  if (from === 'local-only' && to === 'cloud-synced') {
    steps.push(
      'prompt user for passphrase + confirm passphrase (Argon2id KDF will use it)',
      'derive per-record salts + nonces, seal each memory + journal entry with XChaCha20-Poly1305 fallback AES-256-GCM',
      'upload ciphertext + plaintext vectors to cloud storage',
      're-key client-side index for tag matching',
      'record migration timestamp in celiums config',
    );
  } else if (from === 'cloud-synced' && to === 'local-only') {
    steps.push(
      'verify cloud-synced inventory matches local',
      'mark cloud-synced subscription canceled',
      'delete remote ciphertext after operator confirmation',
      'record migration timestamp in celiums config',
    );
  } else if (from === 'cloud-synced' && to === 'cloud-managed') {
    exposesPlaintext = true;
    steps.push(
      'WARN: this migration transitions from ZK to plaintext on the server',
      'require DPA re-acceptance with timestamp + acknowledged-by IP',
      'decrypt local records, upload as plaintext to managed service',
      'update tenant config: mode=cloud-managed, dpa_accepted_at=<timestamp>',
      'record migration timestamp in celiums config',
    );
  } else if (from === 'local-only' && to === 'cloud-managed') {
    exposesPlaintext = true;
    steps.push(
      'WARN: this migration sends plaintext memories to the managed service',
      'require DPA re-acceptance with timestamp + acknowledged-by IP',
      'upload plaintext to managed service',
      'record migration timestamp in celiums config',
    );
  } else if (from === 'cloud-managed' && to === 'cloud-synced') {
    steps.push(
      'prompt user for ZK passphrase',
      'seal each managed record with chosen ZK envelope',
      'replace managed plaintext with ciphertext',
      'rotate managed-service tenant key — old plaintext key is destroyed',
      'record migration timestamp in celiums config',
    );
  } else if (from === 'cloud-managed' && to === 'local-only') {
    steps.push(
      'download all records to local SQLite',
      'detach from managed service',
      'verify counts match',
      'record migration timestamp in celiums config',
    );
  }

  return { from, to, steps, exposesPlaintext };
}
