#!/usr/bin/env node
/**
 * Celiums Memory — interactive SSH setup wizard.
 *
 * Runs as root. Asks the user how they want the dashboard exposed:
 *
 *   1. FQDN mode  — user has a real domain that already points to this
 *                   droplet (A record). Caddy gets auto-TLS via Let's
 *                   Encrypt HTTP-01. URL: https://<their.domain>
 *
 *   2. IP mode    — user just wants something that works now. Caddy
 *                   serves HTTPS with a self-signed cert whose SAN
 *                   includes the droplet's public IPv4. The browser
 *                   shows a warning the user clicks past once.
 *                   URL: https://<droplet-ip>
 *
 * The choice is persisted to /etc/celiums/setup.json so subsequent
 * runs show the current state and offer to reconfigure.
 *
 * After writing /etc/celiums/Caddyfile and (if needed) generating a
 * cert, the script restarts celiums-proxy and writes the public URL
 * to /root/.celiums/dashboard_url so the dashboard's /settings page
 * displays it correctly.
 */

import { promises as fs, existsSync } from 'node:fs';
import { execSync, spawnSync } from 'node:child_process';
import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';

// ─── Paths ──────────────────────────────────────────────────────────
const ETC = '/etc/celiums';
const STATE_FILE = `${ETC}/setup.json`;
const CADDYFILE = `${ETC}/Caddyfile`;
const TLS_DIR = `${ETC}/tls`;
const CERT_FILE = `${TLS_DIR}/server.crt`;
const KEY_FILE = `${TLS_DIR}/server.key`;
const URL_FILE = '/root/.celiums/dashboard_url';

// ─── Helpers ────────────────────────────────────────────────────────
const C = {
  reset: '\x1b[0m', dim: '\x1b[2m', bold: '\x1b[1m',
  green: '\x1b[32m', cyan: '\x1b[36m', yellow: '\x1b[33m',
  red: '\x1b[31m', gray: '\x1b[90m',
};

function print(msg = '') { console.log(msg); }
function ok(msg) { print(`${C.green}✓${C.reset} ${msg}`); }
function warn(msg) { print(`${C.yellow}!${C.reset} ${msg}`); }
function err(msg) { print(`${C.red}✗${C.reset} ${msg}`); }
function step(n, msg) { print(`\n${C.cyan}${C.bold}[${n}]${C.reset} ${msg}`); }

function requireRoot() {
  if (process.getuid && process.getuid() !== 0) {
    err('This script must run as root. Try: sudo celiums-setup');
    process.exit(1);
  }
}

function getPublicIp() {
  // Prefer the IP DigitalOcean exposed; fall back to ifconfig.me.
  for (const cmd of [
    'ip -4 -j route get 1.1.1.1 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin)[0][\\"prefsrc\\"])" 2>/dev/null',
    'curl -fsSL -m 5 https://ifconfig.me 2>/dev/null',
    'curl -fsSL -m 5 https://api.ipify.org 2>/dev/null',
  ]) {
    try {
      const ip = execSync(cmd, { encoding: 'utf8' }).trim();
      if (/^[\d.]+$/.test(ip)) return ip;
    } catch { /* try next */ }
  }
  return null;
}

function isValidFqdn(name) {
  if (!name || name.length > 253) return false;
  // Each label 1-63 chars, alnum + hyphens, no leading/trailing hyphen.
  const label = /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$/i;
  const parts = name.split('.');
  if (parts.length < 2) return false;
  return parts.every((p) => label.test(p));
}

function dnsResolves(name, expectedIp) {
  try {
    const got = execSync(`dig +short +time=4 +tries=2 A ${name} | tail -1`, { encoding: 'utf8' }).trim();
    return { ok: got === expectedIp, got };
  } catch {
    return { ok: false, got: null };
  }
}

async function readState() {
  try {
    const raw = await fs.readFile(STATE_FILE, 'utf8');
    return JSON.parse(raw);
  } catch {
    return { mode: 'unset', completed: false };
  }
}

async function writeState(s) {
  await fs.mkdir(ETC, { recursive: true });
  await fs.writeFile(STATE_FILE, JSON.stringify(s, null, 2), { mode: 0o600 });
}

// ─── Caddyfile templates ────────────────────────────────────────────
function caddyfileForFqdn(fqdn, email) {
  return `# Generated by celiums-setup — FQDN mode (Let's Encrypt auto-TLS).
{
\temail ${email}
\tlog {
\t\toutput stdout
\t\tformat console
\t\tlevel INFO
\t}
}

${fqdn} {
\thandle /v1/*           { reverse_proxy 127.0.0.1:3210 }
\thandle /mcp*           { reverse_proxy 127.0.0.1:3210 }
\thandle /oauth/*        { reverse_proxy 127.0.0.1:3210 }
\thandle /.well-known/*  { reverse_proxy 127.0.0.1:3210 }
\thandle /health         { reverse_proxy 127.0.0.1:3210 }
\thandle                 { reverse_proxy 127.0.0.1:5173 }
}
`;
}

function caddyfileForIp(ip) {
  // Self-signed cert via openssl (generated separately). Caddy serves TLS
  // on :443 with a wildcard match (catches the IP and any Host header).
  return `# Generated by celiums-setup — IP mode (self-signed TLS).
{
\tauto_https off
\tlog {
\t\toutput stdout
\t\tformat console
\t\tlevel INFO
\t}
}

# Plain HTTP redirector → HTTPS.
:80 {
\tredir https://{host}{uri} permanent
}

# HTTPS with the self-signed cert at /etc/celiums/tls/.
:443 {
\ttls ${CERT_FILE} ${KEY_FILE}
\thandle /v1/*           { reverse_proxy 127.0.0.1:3210 }
\thandle /mcp*           { reverse_proxy 127.0.0.1:3210 }
\thandle /oauth/*        { reverse_proxy 127.0.0.1:3210 }
\thandle /.well-known/*  { reverse_proxy 127.0.0.1:3210 }
\thandle /health         { reverse_proxy 127.0.0.1:3210 }
\thandle                 { reverse_proxy 127.0.0.1:5173 }
}
`;
}

// ─── Self-signed cert generation ────────────────────────────────────
async function generateSelfSigned(ip) {
  await fs.mkdir(TLS_DIR, { recursive: true });
  await fs.chmod(TLS_DIR, 0o700);

  // OpenSSL config with IP as SAN. CN must be the IP for older clients.
  const cnf = `${TLS_DIR}/openssl.cnf`;
  await fs.writeFile(cnf, `[req]
distinguished_name = req_dn
req_extensions = v3_req
prompt = no

[req_dn]
C = US
O = Celiums Memory
CN = ${ip}

[v3_req]
keyUsage = digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt

[alt]
IP.1 = ${ip}
DNS.1 = celiums-memory.local
`);

  const r = spawnSync('openssl', [
    'req', '-x509', '-newkey', 'rsa:4096', '-nodes',
    '-keyout', KEY_FILE, '-out', CERT_FILE,
    '-days', '825',
    '-config', cnf, '-extensions', 'v3_req',
  ], { stdio: 'inherit' });
  if (r.status !== 0) throw new Error('openssl failed');

  await fs.chmod(KEY_FILE, 0o600);
  await fs.chmod(CERT_FILE, 0o644);
  // Caddy runs as the celiums user — it must be able to read both.
  spawnSync('chown', ['celiums:celiums', KEY_FILE, CERT_FILE]);
}

// ─── Main flow ──────────────────────────────────────────────────────
async function main() {
  requireRoot();

  print('');
  print(`${C.bold}${C.cyan}╭─────────────────────────────────────────────────────╮${C.reset}`);
  print(`${C.bold}${C.cyan}│${C.reset}  ${C.bold}Celiums Memory — Setup${C.reset}                          ${C.bold}${C.cyan}│${C.reset}`);
  print(`${C.bold}${C.cyan}│${C.reset}  ${C.dim}Choose how you want the dashboard exposed.${C.reset}      ${C.bold}${C.cyan}│${C.reset}`);
  print(`${C.bold}${C.cyan}╰─────────────────────────────────────────────────────╯${C.reset}`);

  const ip = getPublicIp();
  if (!ip) {
    err("Couldn't detect this droplet's public IP. Aborting.");
    process.exit(1);
  }
  print(`\nDetected public IP: ${C.bold}${ip}${C.reset}`);

  const state = await readState();
  if (state.completed) {
    print(`\n${C.dim}Current setup:${C.reset}`);
    print(`  mode  : ${state.mode}`);
    if (state.mode === 'fqdn') print(`  domain: ${state.domain}`);
    if (state.mode === 'ip')   print(`  url   : https://${ip}`);
    print(`  set at: ${state.completedAt}`);
  }

  const rl = createInterface({ input, output });

  step(1, 'Choose access mode');
  print(`  ${C.bold}1)${C.reset} ${C.green}FQDN${C.reset}  Use a domain you control (e.g. memory.example.com).`);
  print(`        ${C.dim}Requires: A record pointing to ${ip}.${C.reset}`);
  print(`        ${C.dim}Cert: Let's Encrypt (free, auto-renewed).${C.reset}`);
  print(`  ${C.bold}2)${C.reset} ${C.yellow}IP${C.reset}    Use https://${ip} directly, no domain.`);
  print(`        ${C.dim}Cert: self-signed (browser shows a warning the first time).${C.reset}`);

  let mode;
  while (true) {
    const ans = (await rl.question('\nChoice [1/2]: ')).trim();
    if (ans === '1') { mode = 'fqdn'; break; }
    if (ans === '2') { mode = 'ip'; break; }
    warn('Type 1 or 2.');
  }

  let fqdn = null;
  let email = null;
  if (mode === 'fqdn') {
    step(2, 'Domain');
    while (true) {
      fqdn = (await rl.question('Domain (e.g. memory.example.com): ')).trim().toLowerCase();
      if (!isValidFqdn(fqdn)) { warn('That doesn\'t look like a valid FQDN.'); continue; }
      print(`  Resolving ${fqdn}…`);
      const r = dnsResolves(fqdn, ip);
      if (r.ok) { ok(`${fqdn} → ${ip} (matches this droplet)`); break; }
      err(`${fqdn} resolves to ${r.got || '(nothing)'}, not ${ip}.`);
      const cont = (await rl.question('Continue anyway? Let\'s Encrypt will fail until DNS propagates [y/N]: ')).trim().toLowerCase();
      if (cont === 'y' || cont === 'yes') break;
    }

    step(3, 'Email for Let\'s Encrypt notifications');
    email = (await rl.question('Email: ')).trim();
    if (!email.includes('@')) email = 'admin@' + fqdn;
  }

  rl.close();

  step(mode === 'fqdn' ? 4 : 2, 'Writing config');

  if (mode === 'ip') {
    print(`  Generating self-signed certificate for ${ip}…`);
    await generateSelfSigned(ip);
    ok(`Cert: ${CERT_FILE}`);
    ok(`Key:  ${KEY_FILE}`);
  }

  const config = mode === 'fqdn' ? caddyfileForFqdn(fqdn, email) : caddyfileForIp(ip);
  await fs.writeFile(CADDYFILE, config, { mode: 0o644 });
  spawnSync('chown', ['celiums:celiums', CADDYFILE]);
  ok(`Caddyfile written to ${CADDYFILE}`);

  // Disable the legacy quick-tunnel + redirect units (idempotent).
  for (const unit of ['celiums-tunnel.service', 'celiums-redirect.service']) {
    spawnSync('systemctl', ['disable', '--now', unit], { stdio: 'ignore' });
  }

  step(mode === 'fqdn' ? 5 : 3, 'Restarting reverse proxy');
  const r = spawnSync('systemctl', ['restart', 'celiums-proxy.service'], { stdio: 'inherit' });
  if (r.status !== 0) {
    err('celiums-proxy.service failed to restart. Check: journalctl -u celiums-proxy -n 50');
    process.exit(1);
  }
  ok('celiums-proxy active');

  // Persist URL for the dashboard /settings page.
  const finalUrl = mode === 'fqdn' ? `https://${fqdn}` : `https://${ip}`;
  await fs.mkdir('/root/.celiums', { recursive: true });
  await fs.writeFile(URL_FILE, finalUrl + '\n', { mode: 0o600 });

  // Persist state so re-runs know what happened.
  await writeState({
    mode,
    domain: fqdn ?? null,
    email: email ?? null,
    ip,
    completed: true,
    completedAt: new Date().toISOString(),
  });

  print('');
  print(`${C.bold}${C.green}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C.reset}`);
  print(`  ${C.bold}Dashboard:${C.reset} ${C.green}${finalUrl}${C.reset}`);
  print(`${C.bold}${C.green}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${C.reset}`);
  print('');

  if (mode === 'ip') {
    warn('Self-signed cert. The first browser visit shows a warning:');
    print('  Chrome/Brave : "Advanced" → "Proceed to <ip> (unsafe)".');
    print('  Firefox      : "Advanced…" → "Accept the Risk and Continue".');
    print('  Safari       : "visit this website" → enter password.');
    print('');
    print(`To remove the warning later, swap to FQDN mode by running:`);
    print(`  ${C.dim}sudo celiums-setup${C.reset}`);
  } else {
    print(`Let\'s Encrypt issues the cert on the first HTTPS request. If`);
    print(`it stalls, watch ${C.dim}journalctl -u celiums-proxy -f${C.reset}.`);
  }
  print('');
}

main().catch((e) => { err(e?.message || String(e)); process.exit(1); });
